### ISSUE TITLE
App when not in foreground, doesn't get messages

### ISSUE THREAD

**Issue by pooran** [jamesmontemagno/XamChat#1]
James, when app when not in foreground, it doesn't get messages. App has to be active to get messages. Will push notifications wake up the app and show the message? Will that complete this app?

**Comment by navkar** [comment]
Yes you have to send a push notification to get the app to foreground. And then the connection is established and you will see messages again.

**Comment by jamesmontemagno** [comment]
Correct. On Android you could configure a background service, but iOS has many restrictions.
